### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by bitten2up** [GeminiCrafterMan/doom-srb220conv#1]
I am somewhat interested in this, I'm just not sure how to use it due to not having much experience with gzdoom

mostly asking because of the cpp code

**Comment by GeminiCrafterMan** [comment]
There is no CPP code, you just run each folder as a PWAD, and the Maps-UDMF WAD file. It's split into sections so you can just have specific parts, i.e. for use with gameplay mods.
